version: 2.1

executors:
  node12:
    working_directory: /home/circleci/port
    docker:
      - image: circleci/node:12
    environment:
      CI: "true"
      ENV: "ci"
      APP: /home/circleci/port
      CACHE: /tmp/caches

commands:
  info:
    description: Start workflow
    steps:
      - hello/circleci-env-highlights
      - hello/system-info

orbs:
  hello: circleci/hello-build@0.0.14
  node: circleci/node@1.1.6
  codecov: codecov/codecov@1.0.5
  packtracker: packtracker/report@2.2.7
  sonarcloud: sonarsource/sonarcloud@1.0.1
  cypress: cypress-io/cypress@1.15.0

workflows:
  version: 2
  default:
    jobs:
      - lint
      - test-unit
      - cypress/run:
          browser: electron
          yarn: true
          record: true
          group: "all tests"
          command: "yarn test:e2e --headless"

jobs:
  lint:
    executor: node12
    steps:
      - checkout
      - info
      - node/with-cache:
          dir: node_modules
          steps:
            - run:
                name: Install all dependencies
                command: yarn install
      - run:
          name: Start check lint via ESlint
          command: yarn lint --no-fix
  test-unit:
    executor: node12
    steps:
      - checkout
      - info
      - node/with-cache:
          dir: node_modules
          steps:
            - run:
                name: Install all dependencies
                command: yarn install
      - run:
          name: Start unit test
          command: yarn test:unit
